name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build uberJar --no-daemon --no-build-cache

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/castboxdownloader-1.0.1-uber.jar
          body: |
            ## Castbox Downloader v${{ github.ref_name }}
            
            ### Installation
            
            1. Download the JAR file
            2. Create an executable script:
            ```bash
            sudo tee /usr/local/bin/castbox-dl << 'EOF'
            #!/bin/bash
            java -jar /opt/castbox-downloader/castbox-downloader.jar
            EOF
            
            sudo chmod +x /usr/local/bin/castbox-dl
            ```
            
            ### Usage
            ```bash
            castbox-dl
            ```
            
            Or run directly:
            ```bash
            java -jar castboxdownloader-1.0.1-uber.jar
            ```